language: haskell
# The version of sh on travis-ci has problems with script parsing when the
# default locale settings are used and the script contains invalid UTF-8 (which
# is one of the things being used in the test suite).
env: LC_ALL=C
